version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - echo "compiling binary..."
      - CGO_ENABLED=0 go build -o bin/helmes ./cmd/helmes
  
  run:
    deps: [build]
    cmds:
      - ./bin/helmes
  
  image:
    cmds:
      - docker build --network host -t helmes:{{.GIT_COMMIT}} .
    vars:
      GIT_COMMIT:
        sh: git rev-parse --short HEAD