version: '3'

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 go build -o bin/helmes ./cmd/helmes
  
  run:
    deps: [build]
    cmds:
      - ./bin/helmes
  
  image:
    cmds:
      - echo "building docker image..."